### ISSUE TITLE
Cucumber Testing requires manual changes to work in Git Bash

### ISSUE THREAD

**Issue by ms14981** [ScottLogic/openapi-forge#156]
This is the section in CONTRIBUTING.md:

> If the testing doesn't work you may be using the wrong script-shell configuration in npm. To keep scripts working in both Unix and Windows machines the shell expected in the project is git-bash. To change your shell type you can run the command below, changing the file location if you have your git-bash executable is in a different location:
> 
> ```
> npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
> ```

For example, in openapi-forge-javascript package.json has this line:

>     "test:generators": "\"./node_modules/.bin/cucumber-js\" -p generators",

This doesn't in Git Bash out of the box. We could use https://www.npmjs.com/package/cross-env so the line above becomes:

>     "test:generators": "cross-env-shell ./node_modules/.bin/cucumber-js -p generators",

- [ ] Fix for JS generator
- [ ] Fix for TS generator

Not needed for C#, the command works in a different way.

**Comment by ColinEberhardt** [comment]
Thanks for raising @ms14981 - see my comment here:

https://github.com/ScottLogic/openapi-forge-javascript/pull/11#issuecomment-1411799808

It would be good to understand a bit more about this issue before merging these changes. Perhaps one to discuss tomorrow?

**Comment by ms14981** [comment]
Resolved
