### ISSUE TITLE
Gherkin tests CI can erroneously pass

### ISSUE THREAD

**Issue by ms14981** [ScottLogic/openapi-forge#157]
`.github/workflows/test.yml` runs this command: `openapi-forge test-generators --format json --generators openapi-forge-javascript openapi-forge-typescript openapi-forge-csharp > test-results.json`. The test results are uploaded, but never checked. If a test run fails, there are logs dumped into this out file, but the CI passes because the file was successfully uploaded.

This ticket is to change the CI so that if there is an error running any tests, or any of the tests run fails, then the workflow should also fail.

The output of a successful run will look like:

```
$ ./src/index.js test-generators -g openapi-forge-javascript openapi-forge-typescript openapi-forge-csharp --format json
Starting tests for generator openapi-forge-javascript
Starting tests for generator openapi-forge-typescript
Starting tests for generator openapi-forge-csharp
{
  "openapi-forge-javascript": {
    "scenarios": 44,
    "failed": 0,
    "passed": 44,
    "time": 17
  },
  "openapi-forge-typescript": {
    "scenarios": 44,
    "failed": 0,
    "passed": 44,
    "time": 50
  },
  "openapi-forge-csharp": {
    "scenarios": 44,
    "failed": 0,
    "passed": 44,
    "time": 49
  }
}
```
We will want to assert (for each generator):

1. The number of scenarios is not zero.
2. The number of failed cases is zero.
3. The number of passed cases equals the number of scenarios.

Note that when we run this command, we do not get the full output from each individual generator, so we cannot say which tests failed, if any did.

**Comment by gkocak-scottlogic** [comment]
Additionally `test-generators` command seems to be exiting with `0` (success) regardless of the outcome of the tests. Even if `continue-on-error: true` statement in the job is removed from the `test.yml` to allow this step to fail, CI would still run with success.

We can change the behaviour on any failed test to a non-zero exit code which can be picked up CI.

**Comment by ms14981** [comment]
Resolved by https://github.com/ScottLogic/openapi-forge/pull/196 and https://github.com/ScottLogic/openapi-forge/pull/194
