### ISSUE TITLE
No way to raise issues with TS generator

### ISSUE THREAD

**Issue by ms14981** [ScottLogic/openapi-forge#188]
![image](https://user-images.githubusercontent.com/15249483/228209467-c8834281-8182-48bc-ae02-64b76a3d33a1.png)

**Comment by ColinEberhardt** [comment]
Good point - @ms14981 @gokberkkocak do you think it is better to have all issues in this repo for visibility? or have generator-specific issues in each repo?

I think perhaps we should allow issue raising for all projects, otherwise people will need a clear sign-post back to this repo for issues.

**Comment by ms14981** [comment]
I personally would prefer to have generator-specific issues, but it's not a big deal.

When I wrote this issue, I thought you could raise issues with the JS and C# generators, but the three are all consistent in not having that section. We would need to change the Java one and signpost people more effectively on all generators.

**Comment by gkocak-scottlogic** [comment]
I don't have a strong prefence one way or the other. But it would be easier to migrate java issues into the main repo and remove the java issue page while giving the necessary redirection.

**Comment by ColinEberhardt** [comment]
Cool, I've opened up issues for all generator projects, thanks for the input.
