### ISSUE TITLE
Version numbers are not updated in package jsons

### ISSUE THREAD

**Issue by ms14981** [ScottLogic/openapi-forge#191]
For the main forge and all the generators, we create git tags which are used by npm. However, it seems like it is recommended to also update the package.json versions: https://docs.npmjs.com/about-semantic-versioning

This seems to have only caused a minor issue so far. In the logs for smoke tests we get packages listed with the package version numbers instead of the git tags versions: `openapi-forge-javascript@0.1.0 prepare`. This will make debugging an issue harder, if the problem was caused by a specific version of a generator (although there likely are ways around this).

You can also see the difference if the main forge is installed locally:

```
$ openapi-forge --version
1.7.0

$ ./src/index.js --version
0.1.0
```

We should either:

1. Correct this going forwards.
2. Ignore the package.json versions and tweak the smoke tests to show the correct version number.

**Comment by ColinEberhardt** [comment]
I think this is a by-product of using the [semantic release](https://github.com/semantic-release/semantic-release) plugin. During the process of publishing to npm, the version number is set 

https://unpkg.com/browse/openapi-forge-javascript@1.4.1/package.json

I presume it does this to stop an update to package.json triggering anther release?

**Comment by ms14981** [comment]
I've updated the smoke testing to show the correct versions in this format:

```
Version of https://github.com/ScottLogic/openapi-forge-typescript installed: v1.4.1
```

So, I'll close this issue as it doesn't seem like a big problem.
