### ISSUE TITLE
Report on generation progress

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#4]
Generation is likely going to be quite rapid, so I don't think a progress bar is needed. However, it would be good to get a report on what the generator is actually doing. Has it located the generator? validated the schema? what files has it generated?

It might also be nice to provide a reassuring message on success

~~~
SUCCESS: API successfully generated, the forge has spewed forth 16 model objects, 7 endpoints, and coughed up a mouthful of smoke.
~~~

And yes, let's give it a bit pf character!

**Comment by jhowlett-scottlogic** [comment]
@ColinEberhardt i would like to work on this issue, can you please assign it to me?

**Comment by ColinEberhardt** [comment]
>  i would like to work on this issue, can you please assign it to me?

Thats great - I've assigned you.

**Comment by jhowlett-scottlogic** [comment]
![openAPI_forge_cl_output](https://user-images.githubusercontent.com/107993905/183438619-806ab553-a2e4-4a29-bcf3-9f0535c53166.png)


Here is a proposed CLI output. I have checked the colours with a [colourblind image generator](https://pilestone.com/pages/color-blindness-simulator-1#) to make sure all text is readable.

**Comment by ColinEberhardt** [comment]
> Here is a proposed CLI output

Looks awesome 🔥

My only suggestion is that we have two version, one which is verbose - which is your example, and one which is more concise, with the concise version as the default.

**Comment by jhowlett-scottlogic** [comment]
> My only suggestion is that we have two version, one which is verbose - which is your example, and one which is more concise, with the concise version as the default.

I like this idea but how concise do we want to be? 

**1st idea**
Turn the bottom part of the verbose output into a one line
```
SUCCESS: Your API has been forged from the fiery furnace: 8 models have been moulded, 13 endpoints have been cast
```

**2nd idea**
Remove ASCII art, some intermediary output lines and the iteration output

```
Cloning generator from 'https://github.com/ScottLogic/openapi-forge-typescript.git'
Cloning into 'C:\Users\jhowlett\AppData\Local\Temp\generatorxcd8tN'...
Validating generator
Loading schema from 'https://petstore3.swagger.io/api/v3/openapi.json'
Validating schema

Iterating over 7 files

Removing temporary folder C:\Users\jhowlett\AppData\Local\Temp\generatorxcd8tN

---------------------------------------------------

            API generation  SUCCESSFUL

---------------------------------------------------

 Your API has been forged from the fiery furnace:
 8 models have been moulded
 13 endpoints have been cast

---------------------------------------------------

```

**Comment by ColinEberhardt** [comment]
I think your 2nd idea looks good to me, thanks.
