### ISSUE TITLE
 Determine the node version requirements for the forge

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#5]
We should determine what node version is required, then determine the best way to document or enforce it

**Comment by jhowlett-scottlogic** [comment]
https://stackoverflow.com/questions/42805913/how-to-find-what-node-version-a-project-supports seems to talk about an engines field in package.json.

This will warn users if they try to install a package on a Node.js version not supported by the package. maybe the could be used? 
Then install previous node versions until one doesn't work.

What about npm?

**Comment by jhowlett-scottlogic** [comment]
Looking at other projects (eslint, commander, prettier) they only state a min node version as npm comes pre-configured when you install node. Therefore i am just adding the node version to the package.json. Also I am usnig the minimum needed for all the generators (forge can be a lower node version compared to TypeScript generator)
