### ISSUE TITLE
Keep openapi-forge dependency up-to-date in language specific generators 

### ISSUE THREAD

**Issue by jhowlett-scottlogic** [ScottLogic/openapi-forge#53]
Find a way to keep the npm devDependency of openapi-forge up to date with the master branch of the openapi-forge GitHub repo. 

Currently it takes the version of openapi-forge that was live at the time of adding to the package.json file (which is now out of date and causes tests to fail).

**Comment by jhowlett-scottlogic** [comment]
Can you assign this to me @ColinEberhardt.

**Comment by ColinEberhardt** [comment]
> Can you assign this to me @ColinEberhardt.

Assigned.

I think we just need to start deploying to npm, and following a proper release / versioning process. I'm keen on [semantic release](https://github.com/semantic-release/semantic-release) having used it in quite a few other projects.

**Comment by jhowlett-scottlogic** [comment]
I think you are right there.

For the time being i will change the package.json to use the current HEAD commit hash of openapi-forge master branch so that the testing works out of the box for anyone that wants to contribute to openapi-forge.

Get that merged in

Then I will then look into generating npm packages for openapi-forge & the language specific generators.

**Comment by jhowlett-scottlogic** [comment]
related to https://github.com/ScottLogic/openapi-forge/issues/7

**Comment by jhowlett-scottlogic** [comment]
https://github.com/ScottLogic/openapi-forge/issues/53
