### ISSUE TITLE
Implement code formatting / linting via CI/CD

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#6]
e.g. apply Prettier

**Comment by jhowlett-scottlogic** [comment]
Is there a preferred CI/CD tech?

**Comment by jhowlett-scottlogic** [comment]
first need https://github.com/ScottLogic/openapi-forge/issues/57 completed and merged

**Comment by jhowlett-scottlogic** [comment]
applied prettier and eslint to openapi-forge, i now must do the same for the two generators.

**Comment by jhowlett-scottlogic** [comment]
linting and formatting has now been implemented for the forge and all generators

**Comment by jhowlett-scottlogic** [comment]
reopened as the PRs havent been merged yet
