### ISSUE TITLE
Supplying file as generator via absolute file path results in failure

### ISSUE THREAD

**Issue by jegor-michejev** [ScottLogic/openapi-forge#63]
Supplying the file via its absolute file path results in generation failing, with the error claiming generator URL "does not end with ".git"

Example: 
generator location: `C:/dev/openapi-forge-typescript`
command: 
```
$ openapi-forge forge 
/ https://petstore3.swagger.io/api/v3/openapi.json 
/ C:/dev/openapi-forge-typescript 
/-o api
```

result:
```
Loading generator from 'C:/dev/openapi-forge-typescript'

---------------------------------------------------

              API generation  FAILED

---------------------------------------------------

Generator URL C:/dev/openapi-forge-typescript does not end with ".git", check that the URL points to a valid generator

---------------------------------------------------
```

if the file location is provided as a relative path (example: `../openapi-forge-typescript`) the generation proceeds as expected

Interestingly, renaming the generator directory to have ".git" at the end will result in a successful generation

Example: 
generator location: `C:/dev/openapi-forge-typescript.git`
command: 
```
$ openapi-forge forge 
/ https://petstore3.swagger.io/api/v3/openapi.json 
/ C:/dev/openapi-forge-typescript.git 
/-o api
```

result:
```
Loading generator from 'C:/dev/openapi-forge-typescript.git'
Validating generator
Loading schema from 'https://petstore3.swagger.io/api/v3/openapi.json'
Validating schema
Iterating over 7 files

---------------------------------------------------

            API generation  SUCCESSFUL

---------------------------------------------------

 Your API has been forged from the fiery furnace:
 8 models have been molded
 13 endpoints have been cast

---------------------------------------------------
```

**Comment by jhowlett-scottlogic** [comment]
Thanks @jegor-michejev for raising this. It seems to be due to the npm package 'url' which doesnt throw an error when generating a URL object in the method.

openapi-forge/src/generate.js:23
```
function isUrl(maybeUrl) {
  try {
    new URL(maybeUrl);
    return true;
  } catch (err) {
    return false;
  }
}
```

**Comment by jhowlett-scottlogic** [comment]
Two possible ways to fix this:

- only allow known protocols (e.g. 'http' & 'https')
- check if local file exists at location, if not treat it as a URL.
