### ISSUE TITLE
Implement a release process

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#7]
Potentially using semantic release

**Comment by jhowlett-scottlogic** [comment]
https://github.com/ScottLogic/openapi-forge/issues/53

**Comment by jhowlett-scottlogic** [comment]
first need https://github.com/ScottLogic/openapi-forge/issues/57 completed and merged

**Comment by ColinEberhardt** [comment]
As an aside, when implementing, can we also add [commitlint](https://github.com/conventional-changelog/commitlint) (or similar), to ensure that commit messages follow the correct convention. We also need to check the default branch settings are appropriate.
