### ISSUE TITLE
Generated files are formatted using prettier (which is JS/TS specific)

### ISSUE THREAD

**Issue by osouthwell-scottlogic** [ScottLogic/openapi-forge#80]
Current formatting of generated files is hard coded for typescript. Ideally this would be based on the generator used.

**Comment by ColinEberhardt** [comment]
There is a slightly immature looking CSharp formatter for Prettier (https://github.com/warrenseine/prettier-plugin-csharp), however, it might make sense to delegate formatting to the generators themselves, allowing them to use language-appropriate tooling.

**Comment by jhowlett-scottlogic** [comment]
delegation of formatting is now at generator level. Currently there is no CSharp formatting because no suitable formater was found
