### ISSUE TITLE
Quiet mode shouldn't suppress errors

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/openapi-forge#82]
I've been testing out some of the changes in a branch, where there was a bug in the generation process. However, in quiet mode, all console output is suppressed. I think we should always show errors

**Comment by jhowlett-scottlogic** [comment]
When developing quiet mode I thought it would eventually be used in an optimised automated environment where printing wouldn't not be read and instead the use of the process' exit code to determine if failed or not. 

However with the use of GitHub Actions, the output is printed and so now yes i agree that quiet should not suppress errors for help in debugging.
