### ISSUE TITLE
Fix CSharp testing for Ubuntu

### ISSUE THREAD

**Issue by jhowlett-scottlogic** [ScottLogic/openapi-forge#84]
The CSharp testing works on a windows and macOS machines but not on Ubuntu machines.

Tested using GitHub Actions runners:
`ubuntu-latest` : does not work
`windows-latest` : works
`macos-latest` : works

Requirements: developer to own a machine running Ubuntu.

This doesn't field like it is high priority, the reasoning is to allow all GitHub Actions to run on all the same runners.

**Comment by ColinEberhardt** [comment]
Migrated to https://github.com/ScottLogic/openapi-forge-csharp/issues/54
